server:
  port: 7070

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   # IMPORTANT (auto routing)
          lower-case-service-id: true

      routes:
        - id: patient-service
          uri: lb://PATIENT-SERVICE
          predicates:
            - Path=/api/patients/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/